In [ ]:
# Lets read the file

In [630]:
import pandas as pd
pp = pd.read_csv("E:\DATA scientist\R\Property price\Property_Price_Train.csv")

In [631]:
pp.head(3)

,Id,Building_Class,Zoning_Class,Lot_Extent,Lot_Size,Road_Type,Lane_Type,Property_Shape,Land_Outline,Utility_Type,Lot_Configuration,Property_Slope,Neighborhood,Condition1,Condition2,House_Type,House_Design,Overall_Material,House_Condition,Construction_Year,Remodel_Year,Roof_Design,Roof_Quality,Exterior1st,Exterior2nd,Brick_Veneer_Type,Brick_Veneer_Area,Exterior_Material,Exterior_Condition,Foundation_Type,Basement_Height,Basement_Condition,Exposure_Level,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,Total_Basement_Area,Heating_Type,Heating_Quality,Air_Conditioning,Electrical_System,First_Floor_Area,Second_Floor_Area,LowQualFinSF,Grade_Living_Area,Underground_Full_Bathroom,Underground_Half_Bathroom,Full_Bathroom_Above_Grade,Half_Bathroom_Above_Grade,Bedroom_Above_Grade,Kitchen_Above_Grade,Kitchen_Quality,Rooms_Above_Grade,Functional_Rate,Fireplaces,Fireplace_Quality,Garage,Garage_Built_Year,Garage_Finish_Year,Garage_Size,Garage_Area,Garage_Quality,Garage_Condition,Pavedd_Drive,W_Deck_Area,Open_Lobby_Area,Enclosed_Lobby_Area,Three_Season_Lobby_Area,Screen_Lobby_Area,Pool_Area,Pool_Quality,Fence_Quality,Miscellaneous_Feature,Miscellaneous_Value,Month_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price
0,1,60,RLD,65.0,8450,Paved,NaN,Reg,Lvl,AllPub,I,GS,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,SS,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PC,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,TF,0,NaN,Attchd,2003.0,RFn,2,1085.793744,TA,TA,Y,163.788080,69.596115,20.337934,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RLD,80.0,9600,Paved,NaN,Reg,Lvl,AllPub,FR2P,GS,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,SS,MetalSd,MetalSd,None,0.0,TA,TA,CB,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,TF,1,TA,Attchd,1976.0,RFn,2,196.316304,TA,TA,Y,198.900074,74.716033,15.039392,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RLD,68.0,11250,Paved,NaN,IR1,Lvl,AllPub,I,GS,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,SS,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PC,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,TF,1,TA,Attchd,2001.0,RFn,2,218.068403,TA,TA,Y,26.127533,32.085268,-46.232198,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500

In [632]:
pp.isnull().sum()

Id                              0
Building_Class                  0
Zoning_Class                    0
Lot_Extent                    259
Lot_Size                        0
Road_Type                       0
Lane_Type                    1368
Property_Shape                  0
Land_Outline                    0
Utility_Type                    0
Lot_Configuration               0
Property_Slope                  0
Neighborhood                    0
Condition1                      0
Condition2                      0
House_Type                      0
House_Design                    0
Overall_Material                0
House_Condition                 0
Construction_Year               0
Remodel_Year                    0
Roof_Design                     0
Roof_Quality                    0
Exterior1st                     0
Exterior2nd                     0
Brick_Veneer_Type               8
Brick_Veneer_Area               8
Exterior_Material               0
Exterior_Condition              0
Foundation_Type                 0
Basement_Height                37
Basement_Condition             37
Exposure_Level                 38
BsmtFinType1                   37
BsmtFinSF1                      0
BsmtFinType2                   38
BsmtFinSF2                      0
BsmtUnfSF                       0
Total_Basement_Area             0
Heating_Type                    0
Heating_Quality                 0
Air_Conditioning                0
Electrical_System               1
First_Floor_Area                0
Second_Floor_Area               0
LowQualFinSF                    0
Grade_Living_Area               0
Underground_Full_Bathroom       0
Underground_Half_Bathroom       0
Full_Bathroom_Above_Grade       0
Half_Bathroom_Above_Grade       0
Bedroom_Above_Grade             0
Kitchen_Above_Grade             0
Kitchen_Quality                 0
Rooms_Above_Grade               0
Functional_Rate                 0
Fireplaces                      0
Fireplace_Quality             689
Garage                         81
Garage_Built_Year              81
Garage_Finish_Year             81
Garage_Size                     0
Garage_Area                     0
Garage_Quality                 81
Garage_Condition               81
Pavedd_Drive                    0
W_Deck_Area                     0
Open_Lobby_Area                 0
Enclosed_Lobby_Area             0
Three_Season_Lobby_Area         0
Screen_Lobby_Area               0
Pool_Area                       0
Pool_Quality                 1452
Fence_Quality                1178
Miscellaneous_Feature        1405
Miscellaneous_Value             0
Month_Sold                      0
Year_Sold                       0
Sale_Type                       0
Sale_Condition                  0
Sale_Price                      0
dtype: int64

In [633]:
# AS we can see, there are many columns which have missing values more than 50% of the observations.
# Hence we decide to drop all those columns.

In [634]:
pp.drop(["Id","Lane_Type","Lot_Extent","Fireplace_Quality","Pool_Quality","Fence_Quality","Miscellaneous_Feature","Total_Basement_Area"],axis=1, inplace = True)

In [635]:
pp.shape

(1459, 73)

In [636]:
# Now, we peroform our Exploratory Data Analysis. 
# We will replace the missing values of the remaining variables.

In [637]:
pp.Basement_Height.value_counts()

TA    648
Gd    618
Ex    121
Fa     35
Name: Basement_Height, dtype: int64

In [638]:
pp.Basement_Height = pp.Basement_Height.fillna("TA")
pp.Basement_Height.isnull().sum()

0

In [639]:
pp.Basement_Condition.value_counts()

TA    1310
Gd      65
Fa      45
Po       2
Name: Basement_Condition, dtype: int64

In [640]:
pp.Basement_Condition = pp.Basement_Condition.fillna("TA")
pp.Basement_Condition.isnull().sum()

0

In [641]:
pp.Exposure_Level.value_counts()

No    952
Av    221
Gd    134
Mn    114
Name: Exposure_Level, dtype: int64

In [642]:
pp.Exposure_Level = pp.Exposure_Level.fillna("No")
pp.Exposure_Level.isnull().sum()

0

In [643]:
pp.BsmtFinType1.value_counts()

Unf    430
GLQ    418
ALQ    220
BLQ    147
Rec    133
LwQ     74
Name: BsmtFinType1, dtype: int64

In [644]:
pp.BsmtFinType1 = pp.BsmtFinType1.fillna("Unf")
pp.BsmtFinType1.isnull().sum()

0

In [645]:
pp.BsmtFinType2.value_counts()

Unf    1256
Rec      54
LwQ      45
BLQ      33
ALQ      19
GLQ      14
Name: BsmtFinType2, dtype: int64

In [646]:
pp.BsmtFinType2 = pp.BsmtFinType2.fillna("Unf")
pp.BsmtFinType2.isnull().sum()

0

In [647]:
pp.Electrical_System.value_counts()

SBrkr    1333
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: Electrical_System, dtype: int64

In [648]:
pp.Electrical_System = pp.Electrical_System.fillna("SBrkr")
pp.Electrical_System.isnull().sum()

0

In [649]:
pp.Garage.value_counts()

Attchd     869
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2TFes        5
2Types       1
Name: Garage, dtype: int64

In [650]:
pp.Garage_Built_Year = pp.Garage_Built_Year.fillna(2005)
pp.Garage_Built_Year.isnull().sum()

0

In [651]:
pp.Garage_Finish_Year.value_counts()

Unf    605
RFn    422
Fin    351
Name: Garage_Finish_Year, dtype: int64

In [652]:
pp.Garage_Finish_Year = pp.Garage_Finish_Year.fillna("Unf")
pp.Garage_Finish_Year.isnull().sum()

0

In [653]:
pp.Garage_Quality.value_counts()

TA    1310
Fa      48
Gd      14
Po       3
Ex       3
Name: Garage_Quality, dtype: int64

In [654]:
pp.Garage_Quality = pp.Garage_Quality.fillna("TA")
pp.Garage_Quality.isnull().sum()

0

In [655]:
pp.Garage_Condition.value_counts()

TA    1325
Fa      35
Gd       9
Po       7
Ex       2
Name: Garage_Condition, dtype: int64

In [656]:
pp.Garage_Condition = pp.Garage_Condition.fillna("TA")
pp.Garage_Condition.isnull().sum()

0

In [657]:
pp.Brick_Veneer_Area = pp.Brick_Veneer_Area.fillna(pp.Brick_Veneer_Area.mean())
pp.Brick_Veneer_Area.isnull().sum()

0

In [658]:
pp.Brick_Veneer_Type.value_counts()

None       863
BrkFace    445
Stone      128
BrkCmn      15
Name: Brick_Veneer_Type, dtype: int64

In [659]:
pp.Brick_Veneer_Area = pp.Brick_Veneer_Area.fillna(pp.Brick_Veneer_Area.mean())
pp.Brick_Veneer_Area.isnull().sum()

0

In [660]:
pp.Garage = pp.Garage.fillna("Attchd")
pp.Garage.isnull().sum()

0

In [661]:
pp.drop("Brick_Veneer_Type",axis=1, inplace = True)

In [662]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
pp.isnull().sum()

Building_Class               0
Zoning_Class                 0
Lot_Size                     0
Road_Type                    0
Property_Shape               0
Land_Outline                 0
Utility_Type                 0
Lot_Configuration            0
Property_Slope               0
Neighborhood                 0
Condition1                   0
Condition2                   0
House_Type                   0
House_Design                 0
Overall_Material             0
House_Condition              0
Construction_Year            0
Remodel_Year                 0
Roof_Design                  0
Roof_Quality                 0
Exterior1st                  0
Exterior2nd                  0
Brick_Veneer_Area            0
Exterior_Material            0
Exterior_Condition           0
Foundation_Type              0
Basement_Height              0
Basement_Condition           0
Exposure_Level               0
BsmtFinType1                 0
BsmtFinSF1                   0
BsmtFinType2                 0
BsmtFinSF2                   0
BsmtUnfSF                    0
Heating_Type                 0
Heating_Quality              0
Air_Conditioning             0
Electrical_System            0
First_Floor_Area             0
Second_Floor_Area            0
LowQualFinSF                 0
Grade_Living_Area            0
Underground_Full_Bathroom    0
Underground_Half_Bathroom    0
Full_Bathroom_Above_Grade    0
Half_Bathroom_Above_Grade    0
Bedroom_Above_Grade          0
Kitchen_Above_Grade          0
Kitchen_Quality              0
Rooms_Above_Grade            0
Functional_Rate              0
Fireplaces                   0
Garage                       0
Garage_Built_Year            0
Garage_Finish_Year           0
Garage_Size                  0
Garage_Area                  0
Garage_Quality               0
Garage_Condition             0
Pavedd_Drive                 0
W_Deck_Area                  0
Open_Lobby_Area              0
Enclosed_Lobby_Area          0
Three_Season_Lobby_Area      0
Screen_Lobby_Area            0
Pool_Area                    0
Miscellaneous_Value          0
Month_Sold                   0
Year_Sold                    0
Sale_Type                    0
Sale_Condition               0
Sale_Price                   0
dtype: int64

In [663]:
# We are going to use Label Encoder from sklearn library to convert the data into numeric format.

In [664]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
pp.Zoning_Class = le.fit_transform(pp.Zoning_Class)

In [665]:
pp.Road_Type = le.fit_transform(pp.Road_Type)
pp.Property_Shape = le.fit_transform(pp.Property_Shape)
pp.Land_Outline = le.fit_transform(pp.Land_Outline)
pp.Utility_Type = le.fit_transform(pp.Utility_Type)
pp.Lot_Configuration = le.fit_transform(pp.Lot_Configuration)
pp.Property_Slope = le.fit_transform(pp.Property_Slope)
pp.Neighborhood = le.fit_transform(pp.Neighborhood)
pp.Condition1= le.fit_transform(pp.Condition1)
pp.Condition2 = le.fit_transform(pp.Condition2)
pp.House_Type = le.fit_transform(pp.House_Type)
pp.House_Design = le.fit_transform(pp.House_Design)
pp.Roof_Design = le.fit_transform(pp.Roof_Design)
pp.Roof_Quality = le.fit_transform(pp.Roof_Quality)
pp.Exterior1st = le.fit_transform(pp.Exterior1st)
pp.Exterior2nd = le.fit_transform(pp.Exterior2nd)
pp.Exterior_Material = le.fit_transform(pp.Exterior_Material)
pp.Exterior_Condition = le.fit_transform(pp.Exterior_Condition)
pp.Foundation_Type = le.fit_transform(pp.Foundation_Type)
pp.Basement_Height = le.fit_transform(pp.Basement_Height)
pp.Basement_Condition = le.fit_transform(pp.Basement_Condition)
pp.Exposure_Level = le.fit_transform(pp.Exposure_Level)
pp.BsmtFinType1 = le.fit_transform(pp.BsmtFinType1)
pp.BsmtFinType2 = le.fit_transform(pp.BsmtFinType2)
pp.Heating_Type = le.fit_transform(pp.Heating_Type)
pp.Heating_Quality = le.fit_transform(pp.Heating_Quality)
pp.Air_Conditioning = le.fit_transform(pp.Air_Conditioning)
pp.Electrical_System = le.fit_transform(pp.Electrical_System)
pp.Kitchen_Quality = le.fit_transform(pp.Kitchen_Quality)
pp.Functional_Rate = le.fit_transform(pp.Functional_Rate)
pp.Garage_Finish_Year = le.fit_transform(pp.Garage_Finish_Year)
pp.Garage_Quality = le.fit_transform(pp.Garage_Quality)
pp.Garage_Condition = le.fit_transform(pp.Garage_Condition)
pp.Pavedd_Drive = le.fit_transform(pp.Pavedd_Drive)
pp.Sale_Type = le.fit_transform(pp.Sale_Type)
pp.Sale_Condition = le.fit_transform(pp.Sale_Condition)
pp.Garage = le.fit_transform(pp.Garage)

In [666]:
import numpy as np
pp["Brick_Veneer_Area"] = pp.Brick_Veneer_Area.astype(int)
pp["Garage_Built_Year"] = pp.Garage_Built_Year.astype(int)

In [667]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
pp.head(30)

,Building_Class,Zoning_Class,Lot_Size,Road_Type,Property_Shape,Land_Outline,Utility_Type,Lot_Configuration,Property_Slope,Neighborhood,Condition1,Condition2,House_Type,House_Design,Overall_Material,House_Condition,Construction_Year,Remodel_Year,Roof_Design,Roof_Quality,Exterior1st,Exterior2nd,Brick_Veneer_Area,Exterior_Material,Exterior_Condition,Foundation_Type,Basement_Height,Basement_Condition,Exposure_Level,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,Heating_Type,Heating_Quality,Air_Conditioning,Electrical_System,First_Floor_Area,Second_Floor_Area,LowQualFinSF,Grade_Living_Area,Underground_Full_Bathroom,Underground_Half_Bathroom,Full_Bathroom_Above_Grade,Half_Bathroom_Above_Grade,Bedroom_Above_Grade,Kitchen_Above_Grade,Kitchen_Quality,Rooms_Above_Grade,Functional_Rate,Fireplaces,Garage,Garage_Built_Year,Garage_Finish_Year,Garage_Size,Garage_Area,Garage_Quality,Garage_Condition,Pavedd_Drive,W_Deck_Area,Open_Lobby_Area,Enclosed_Lobby_Area,Three_Season_Lobby_Area,Screen_Lobby_Area,Pool_Area,Miscellaneous_Value,Month_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price
0,60,3,8450,1,3,3,0,4,0,5,2,2,0,5,7,5,2003,2003,1,4,12,13,196,2,4,2,2,3,3,2,706,5,0,150,1,0,1,4,856,854,0,1710,1,0,2,1,3,1,2,8,7,0,2,2003,1,2,1085.793744,4,4,2,163.788080,69.596115,20.337934,0,0,0,0,2,2008,8,4,208500
1,20,3,9600,1,3,3,0,2,0,24,1,2,0,2,6,8,1976,1976,1,4,8,8,0,3,4,1,2,3,1,0,978,5,0,284,1,0,1,4,1262,0,0,1262,0,1,2,0,3,1,3,6,7,1,2,1976,1,2,196.316304,4,4,2,198.900074,74.716033,15.039392,0,0,0,0,5,2007,8,4,181500
2,60,3,11250,1,0,3,0,4,0,5,2,2,0,5,7,5,2001,2002,1,4,12,13,162,2,4,2,2,3,2,2,486,5,0,434,1,0,1,4,920,866,0,1786,1,0,2,1,3,1,2,6,7,1,2,2001,1,2,218.068403,4,4,2,26.127533,32.085268,-46.232198,0,0,0,0,9,2008,8,4,223500
3,70,3,9550,1,0,3,0,0,0,6,2,2,0,5,7,5,1915,1970,1,4,13,15,0,3,4,0,3,1,3,0,216,5,0,540,1,2,1,4,961,756,0,1717,1,0,1,0,3,1,2,7,7,1,6,1998,2,3,696.996439,4,4,2,46.948018,40.181415,60.921821,0,0,0,0,2,2006,8,0,140000
4,60,3,14260,1,0,3,0,2,0,15,2,2,0,5,8,5,2000,2000,1,4,12,13,350,2,4,2,2,3,0,2,655,5,0,490,1,0,1,4,1145,1053,0,2198,1,0,2,1,4,1,2,9,7,1,2,2000,1,3,568.859882,4,4,2,-10.626105,20.755323,21.788818,0,0,0,0,12,2008,8,4,250000
5,50,3,14115,1,0,3,0,4,0,11,2,2,0,0,5,5,1993,1995,1,4,12,13,0,3,4,5,2,3,3,2,732,5,0,64,1,0,1,4,796,566,0,1362,1,0,1,1,1,1,3,5,7,0,2,1993,2,2,703.481359,4,4,2,0.621402,36.740335,70.350362,320,0,0,700,10,2009,8,4,143000
6,20,3,10084,1,3,3,0,4,0,21,2,2,0,2,8,5,2004,2005,1,4,12,13,186,2,4,2,0,3,0,2,1369,5,0,317,1,0,1,4,1694,0,0,1694,1,0,2,0,3,1,2,7,7,1,2,2004,1,2,555.415694,4,4,2,39.047177,118.613457,-7.064622,0,0,0,0,8,2007,8,4,307000
7,60,3,10382,1,0,3,0,0,0,14,4,2,0,5,7,6,1973,1973,1,4,6,6,240,3,4,1,2,3,2,0,859,1,32,216,1,0,1,4,1107,983,0,2090,1,0,2,1,3,1,3,7,7,2,2,1973,1,2,737.632993,4,4,2,201.101046,150.621507,76.923944,0,0,0,350,11,2009,8,4,200000
8,50,4,6120,1,3,3,0,4,0,17,0,2,0,0,7,5,1931,1950,1,4,3,15,0,3,4,0,3,3,3,5,0,5,0,952,1,2,1,1,1022,752,0,1774,0,0,2,0,2,2,3,8,1,2,6,1931,2,2,424.620043,1,4,2,-24.044684,57.933986,78.563161,0,0,0,0,4,2008,8,0,129900
9,190,3,7420,1,3,3,0,0,0,3,0,0,1,1,5,6,1939,1950,1,4,8,8,0,3,4,0,3,3,3,2,851,5,0,140,1,0,1,4,1077,0,0,1077,1,0,1,0,2,2,3,5,7,2,2,1939,1,1,632.539240,2,4,2,31.123219,59.827696,57.757631,0,0,0,0,1,2008,8,4,118000
10,20,3,11200,1,3,3,0,4,0,19,2,2,0,2,5,5,1965,1965,3,4,6,6,0,3,4,1,3,3,3,4,906,5,0,134,1,0,1,4,1040,0,0,1040,1,0,1,0,3,1,3,5,7,0,6,1965,2,1,724.509882,4,4,2,185.564715,22.519851,30.478397,0,0,0,0,2,2008,8,4,129500
11,60,3,11924,1,0,3,0,4,0,16,2,2,0,5,9,5,2005,2006,3,4,14,15,286,0,4,2,0,3,3,2,998,5,0,177,1,0,1,4,1182,1142,0,2324,1,0,3,0,4,1,0,11,7,2,4,2005,0,3,1004.528225,4,4,2,141.036757,23.533718,103.990776,0,0,0,0,7,2006,6,5,345000
12,20,3,12968,1,1,3,0,4,0,19,2,2,0,2,5,6,1962,1962,3,4,6,10,0,3,4,1,3,3,3,0,737,5,0,175,1,4,1,4,912,0,0,912,1,0,1,0,2,1,3,4,7,0,6,1962,2,1,450.890177,4,4,2,129.053257,98.369624,19.654410,0,176,0,0,9,2008,8,4,144000
13,20,3,10652,1,0,3,0,4,0,5,2,2,0,2,7,5,2006,2007,1,4,12,13,306,2,4,2,2,3,0,5,0,5,0,1494,1,0,1,4,1494,0,0,1494,0,0,2,0,3,1,2,7,7,1,2,2006,1,3,520.909729,4,4,2,183.650980,-14.203250,75.125931,0,0,0,0,8,2007,6,5,279500
14,20,3,10920,1,0,3,0,0,0,12,2,2,0,2,6,5,1960,1960,3,4,8,8,212,3,4,1,3,3,3,1,733,5,0,520,1,4,1,4,1253,0,0,1253,1,0,1,1,2,1,3,5,7,1,2,1960,1,1,690.004706,4,4,2,199.914549,6.475976,100.205972,0,0,0,0,5,2008,8,4,157000
15,45,4,6120,1,3,3,0,0,0,3,2,2,0,1,7,8,1929,2001,1,4,13,14,0,3,4,0,3,3,3,5,0,5,0,832,1,0,1,0,854,0,0,854,0,0,1,0,2,1,3,5,7,0,6,1991,2,2,620.143245,4,4,2,34.684125,105.163413,-58.762360,0,0,0,0,7,2007,8,4,132000
16,20,3,11241,1,0,3,0,1,0,12,2,2,0,2,6,7,1970,1970,1,4,13,14,180,3,4,1,3,3,3,0,578,5,0,426,1,0,1,4,1004,0,0,1004,1,0,1,0,2,1,3,5,7,1,2,1970,0,2,506.333575,4,4,2,195.926552,154.382283,119.542437,0,0,0,700,3,2010,8,4,149000
17,90,3,10791,1,3,3,0,4,0,19,2,2,2,2,4,5,1967,1967,1,4,8,8,0,3,4,4,3,3,3,5,0,5,0,0,1,4,1,4,1296,0,0,1296,0,0,2,0,2,2,3,6,7,0,5,1967,2,2,200.203887,4,4,2,114.159130,4.615600,-13.433509,0,0,0,500,10,2006,8,4,90000
18,20,3,13695,1,3,3,0,4,0,20,5,2,0,2,5,5,2004,2004,1,4,12,13,0,3,4,2,3,3,3,2,646,5,0,468,1,0,1,4,1114,0,0,1114,1,0,1,1,3,1,2,6,7,0,6,2004,2,2,425.825400,4,4,2,88.650284,40.701852,-20.468547,0,0,0,0,6,2008,8,4,159000
19,20,3,7560,1,3,3,0,4,0,12,2,2,0,2,5,6,1958,1965,3,4,3,10,0,3,4,1,3,3,3,3,504,5,0,525,1,4,1,4,1339,0,0,1339,0,0,1,0,3,1,3,6,1,0,2,1958,2,1,371.162160,4,4,2,141.062720,146.374343,47.206992,0,0,0,0,5,2009,0,0,139000
20,60,3,14215,1,0,3,0,0,0,16,2,2,0,5,8,5,2005,2006,1,4,12,13,380,2,4,2,0,3,0,5,0,5,0,1158,1,0,1,4,1158,1218,0,2376,0,0,3,1,4,1,2,9,7,1,4,2005,1,3,310.453972,4,4,2,-143.043667,-9.930688,52.136593,0,0,0,0,11,2006,6,5,325300
21,45,4,7449,1,3,0,0,4,0,9,2,2,0,1,7,7,1930,1950,1,4,13,14,0,3,4,2,3,3,3,5,0,5,0,637,1,0,1,1,1108,0,0,1108,0,0,1,0,3,1,2,6,7,1,2,1930,2,1,424.248641,4,4,0,33.626708,-55.035381,-19.392093,0,0,0,0,6,2007,8,4,139400
22,20,3,9742,1,3,3,0,4,0,5,2,2,0,2,8,5,2002,2002,3,4,12,13,281,2,4,2,2,3,3,5,0,5,0,1777,1,0,1,4,1795,0,0,1795,0,0,2,0,3,1,2,7,7,1,2,2002,1,2,360.783209,4,4,2,94.328411,-143.853710,5.708471,0,0,0,0,9,2008,8,4,230000
23,120,4,4224,1,3,3,0,4,0,10,2,2,4,2,5,7,1976,1976,1,4,5,5,0,3,4,2,2,3,3,2,840,5,0,200,1,4,1,4,1060,0,0,1060,1,0,1,0,3,1,3,6,7,1,2,1976,2,2,335.767254,4,4,2,-116.956767,-29.982228,135.504072,0,0,0,0,6,2007,8,4,129900
24,20,3,8246,1,0,3,0,4,0,19,2,2,0,2,5,8,1968,2001,1,4,9,10,0,3,2,1,3,3,2,4,188,0,668,204,1,0,1,4,1060,0,0,1060,1,0,1,0,3,1,2,6,7,1,2,1968,2,1,603.217539,4,4,2,120.924036,30.573588,16.232561,0,0,0,0,5,2010,8,4,154000
25,20,3,14230,1,3,3,0,0,0,16,2,2,0,2,8,5,2007,2007,1,4,12,13,640,2,4,2,2,3,3,5,0,5,0,1566,1,0,1,4,1600,0,0,1600,0,0,2,0,3,1,2,7,7,1,2,2007,1,3,750.869337,4,4,2,104.552285,30.299500,2.502045,0,0,0,0,7,2009,8,4,256300
26,20,3,7200,1,3,3,0,0,0,12,2,2,0,2,5,7,1951,2000,1,4,13,14,0,3,4,1,3,3,2,1,234,4,486,180,1,4,1,4,900,0,0,900,0,1,1,0,3,1,2,5,7,0,6,2005,2,2,685.330199,4,4,2,-4.995048,49.715385,-14.667328,0,0,0,0,5,2010,8,4,134800
27,20,3,11478,1,3,3,0,4,0,16,2,2,0,2,8,5,2007,2008,1,4,12,13,200,2,4,2,0,3,3,2,1218,5,0,486,1,0,1,4,1704,0,0,1704,1,0,2,0,3,1,2,7,7,1,2,2008,1,3,568.564476,4,4,2,99.744860,25.698776,108.289274,0,0,0,0,5,2010,8,4,306000
28,20,3,16321,1,0,3,0,1,0,12,2,2,0,2,5,6,1957,1997,1,4,8,8,0,3,4,1,3,3,1,1,1277,5,0,207,1,4,1,4,1600,0,0,1600,1,0,1,0,2,1,3,6,7,2,2,1957,1,1,804.643306,4,4,2,162.292667,-111.552486,30.667814,0,0,0,0,12,2006,8,4,207500
29,30,4,6324,1,0,3,0,4,0,3,1,7,0,2,4,6,1927,1950,1,4,8,8,0,3,4,0,3,3,3,5,0,5,0,520,1,1,0,4,520,0,0,520,0,0,1,0,1,1,1,4,7,0,6,1920,2,1,563.256140,1,4,2,150.473330,-76.901359,90.370002,0,0,0,0,5,2008,8,4,68500

In [668]:
pp.shape

(1459, 72)

In [669]:
# The Eexploratory Data Analysis is completed.
# And we will perform random sampling on our model and build Linear regression on our datset.

In [670]:
pp_x = pp.iloc[:,1:71]
pp_y = pp.iloc[:,-1]

In [671]:
from sklearn.model_selection import train_test_split
pp_x_train, pp_x_test,pp_y_train,pp_y_test = train_test_split(pp_x,pp_y,test_size = 0.2)

In [672]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [677]:
reg.fit(pp_x_train,pp_y_train)

LinearRegression()

In [678]:
pred_test = reg.predict(pp_x_test)

In [679]:
error = abs(pp_y_test - pred_test)

In [680]:
import numpy as np
np.mean(error)

21332.502454091835

In [681]:
MAPE = np.mean(np.abs(error * 100/ pp_y_test))
MAPE

12.134544439790055

In [682]:
Accuracy = 100 - MAPE
Accuracy

87.86545556020994

In [ ]:
# The accuracy of the model is 87.86%.